### ISSUE TITLE
Quansight / jaeger-browser 

### ISSUE THREAD

**Issue by nehagupta84** [uber/jaeger-client-javascript#7]
Hi All,

I was exploring on jaeger support for browser and came across this library, so there are 2 questions i have -

1. Does this supports integration with existing jaeger library. example
     
   vue.js . -> node js --> dot net code
   
for vue i would want to use this for node and other will use jaeger library, so will be able to apss context from vue to rest api's.?

2. I was trying to use this in vue.js and it gives me below error

Access to fetch at 'http://localhost:14268/inject-span' from origin 'https://myappURLlocalhost:1024' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

It will be really great if you could help me with this.

**Comment by saulshanabrook** [comment]
Are these questions directed towards the https://github.com/Quansight/jaeger-browser project?

If yes, in response to 1. it is agnostic to JS frontend libraries. I have not used it with Vue. However it is setup to work with the Python server provided their not a Node server. Although of course if you implemented the same API in Node it should work.

In response to 2, you are using the python package provided there, it should be [disabling all CORS restrictions](https://github.com/Quansight/jaeger-browser/blob/f3f7d055fb3436c80620ccfe8c34fe2c0f94767a/jaeger_browser/__init__.py#L35).

The logs from the server might give more details.
